[package]
name = "multilinear_extensions"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ff.workspace = true
ark-std.workspace = true
rayon.workspace = true
goldilocks = { path = "../goldilocks" }