[package]
name = "transcript"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ff.workspace = true
ark-std.workspace = true
rayon.workspace = true
serde.workspace = true
goldilocks = { path = "../goldilocks" }
